<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Client Ccmp' => '',
  'Create Delivery Type' => '',
  'Create Order' => '',
  'Create Pf Delivery Type' => '',
  'Cubic meters' => '',
  'Date' => '',
  'Delivery Types' => '',
  'Delivery type' => '',
  'Desired date' => '',
  'Groupage' => '',
  'ID' => '',
  'Internal notes' => '',
  'Load meters' => '',
  'Loading meters' => '',
  'Manufacturer' => '',
  'Notes' => '',
  'Number' => '',
  'Order' => '',
  'Order Items' => '',
  'Orders' => '',
  'Planed ready date' => '',
  'Planned delivery date' => 'Planned delivery',
  'Planned delivery type' => '',
  'Planned dispath date' => '',
  'STATUS_DELIVERED' => 'Delivered',
  'STATUS_DELIVERY' => 'Delivery',
  'STATUS_PLANING' => 'Planning',
  'STATUS_READY' => 'Ready',
  'Status' => '',
  'Week Number' => '',
  'tooltip.client_ccmp_id' => '',
  'tooltip.desired_date' => '',
  'tooltip.groupage' => '',
  'tooltip.id' => '',
  'tooltip.load_meters' => '',
  'tooltip.name' => '',
  'tooltip.notes' => '',
  'tooltip.number' => '',
  'tooltip.order_date' => '',
  'tooltip.planed_delivery_date' => '',
  'tooltip.planed_delivery_type' => '',
  'tooltip.planed_dispatch_date' => '',
  'tooltip.status' => '',
);
